workflows/ansible-setup: add test report generation
Add the test report generation in the ansible-setup workflow pipeline.
The added jobs are based on the existing SEAPATH workflows to generate
a test report.

Signed-off-by: Paul Le Guen de Kerneizon <paul.leguendekerneizon@savoirfairelinux.com>

diff --git a/.github/workflows/ansible-setup.yml b/.github/workflows/ansible-setup.yml
--- a/.github/workflows/ansible-setup.yml
+++ b/.github/workflows/ansible-setup.yml
@@ -38,6 +38,9 @@ jobs:
     runs-on: ubuntu-24.04
     timeout-minutes: 90
     env:
+      HYPERVISOR_INVENTORY: ${{ github.workspace }}/virtual-cluster/inventory/seapath-sandbox.yaml
+      VM_INVENTORY: ${{ github.workspace }}/virtual-cluster/inventory/seapath-test-vm.yaml
+      RESULTS_FOLDER: ${{ github.workspace }}/ansible/test_results
       LIBVIRT_DEFAULT_URI: qemu:///system
       ANSIBLE_HOST_KEY_CHECKING: "False"
       TF_CLI_ARGS_apply: "-auto-approve"
@@ -47,11 +50,14 @@ jobs:
       ANSIBLE_REPO: "${{ github.workspace }}"
       VIRTUAL_CLUSTER_REPO: "${{ github.workspace }}/virtual-cluster"
     steps:
-      - uses: actions/checkout@v4
+      - uses: actions/checkout@v7
 
-      - name: Clone virtual-cluster repository
-        run : |
-          git clone https://github.com/seapath/virtual-cluster.git
+      - name: Checkout virtual-cluster
+        uses: actions/checkout@v6
+        with:
+          repository: seapath/virtual-cluster.git
+          path: virtual-cluster
+          ref: main
 
       - name: Install system dependencies
         run: |
@@ -77,6 +83,9 @@ jobs:
             | sudo tee /etc/apt/sources.list.d/hashicorp.list
           sudo apt-get update
           sudo apt-get install -y terraform
+
+          curl -LO https://github.com/savoirfairelinux/cqfd/releases/download/v5.10.2/cqfd_5.10.2_all.deb
+          sudo apt install ./cqfd_5.10.2_all.deb
 
       - name: Enable libvirt + Open vSwitch and grant runner access
         run: |
@@ -207,49 +216,173 @@ jobs:
             done
 
       - name: Grow root partition and filesystem
+        working-directory: virtual-cluster
         run: |
-          cd $VIRTUAL_CLUSTER_REPO
           sg libvirt -c 'make ansible-grow-rootfs'
 
       - name: ansible-ping
+        working-directory: virtual-cluster
         run: |
-          cd $VIRTUAL_CLUSTER_REPO
           sg libvirt -c 'make ansible-ping'
 
       - name: ansible-setup
+        working-directory: virtual-cluster
         run: |
-          cd $VIRTUAL_CLUSTER_REPO
           sg libvirt -c 'make ansible-setup'
 
       - name: Deploy a VM in the SEAPATH cluster
+        working-directory: virtual-cluster
         run: |
-          cd $VIRTUAL_CLUSTER_REPO
           sg libvirt -c 'make ansible-deploy-vm'
+
+      - name: Checkout test-report-pdf
+        uses: actions/checkout@v6
+        with:
+          repository: savoirfairelinux/test-report-pdf
+          path: test-report-pdf
+
+      - name: Prepare report metadatas
+        run: |
+          set -euxo pipefail
+          cd $ANSIBLE_REPO
+          cqfd init
+          # Create a JSON object with data about the hypervisors
+          hyp=$(cqfd exec ansible-inventory --list \
+            ${{ env.HYPERVISOR_INVENTORY }} \
+            --limit "standalone_machine,cluster_machines" \
+            2> /dev/null | jq -c .)
+
+          hyp_pretty_list=$(echo "$hyp" | jq -r 'keys | join(", ")')
+          echo "Running on hypervisors $hyp_pretty_list"
+          echo "HYPERVISOR_INVENTORY_JSON=$hyp" >> "$GITHUB_ENV"
+
+          # Create a JSON object with data about the VMs
+          vms=$(cqfd exec ansible-inventory --list \
+            ${{ env.VM_INVENTORY }} \
+            --limit "VMs" \
+            2>/dev/null | jq -c .)
+
+          vms_pretty_list=$(echo "$vms" | jq -r 'to_entries | map(if .value.rt then .key + " (RT)" else .key end) | join(", ")')
+          echo "Deployed VMs $vms_pretty_list"
+
+          echo "VM_INVENTORY_JSON=$vms" >> "$GITHUB_ENV"
+
+      - name: Prepare report generation
+        working-directory: test-report-pdf
+        run: |
+          cqfd init
+          mkdir -p ${{ env.RESULTS_FOLDER }}
+          mkdir -p include
+          cp ${{ env.ANSIBLE_REPO }}/.github/test-report/prerequisites.adoc.j2 include/
+
+          echo "$HYPERVISOR_INVENTORY_JSON" "$VM_INVENTORY_JSON" | jq --slurp '{hypervisors: .[0], vms: .[1]}' > ${{ env.RESULTS_FOLDER }}/data.json
+
+      - name: Fetch hypervisors information
+        run: |
+          cd $ANSIBLE_REPO
+          # Those run args allow to have a clean JSON output that can be parsed.
+          ANSIBLE_HOST_PATTERN_MISMATCH=ignore \
+          ANSIBLE_LOAD_CALLBACK_PLUGINS=true \
+          ANSIBLE_STDOUT_CALLBACK=json \
+          ANSIBLE_CALLBACKS_ENABLED=null \
+          ansible \
+            standalone_machine,cluster_machines \
+            -i ${{ env.HYPERVISOR_INVENTORY }} \
+            --module-name setup \
+            | jq '.plays[0].tasks[0].hosts | {host_facts: with_entries(.value = .value.ansible_facts)}' \
+            > ${{ env.RESULTS_FOLDER }}/hypervisors_facts.json
 
       - name: Run Cukinia tests on all hypervisor nodes
         run: |
-          cd $VIRTUAL_CLUSTER_REPO
-          sg libvirt -c 'make ansible-cukinia-tests'
+          cd $ANSIBLE_REPO
+          ansible-playbook \
+            -i ${{ env.HYPERVISOR_INVENTORY }} \
+            --limit "standalone_machine,cluster_machines" \
+            playbooks/ci_test.yaml \
+            --extra-vars "cukinia_test_prefix=/${{ env.RESULTS_FOLDER
+            }}" \
 
       - name: Check Cukinia tests results
+        working-directory: ansible
         # NOTE: Tests 109, 28, 31 and 32 are not compatible in a
         # virtualized environment, so ignore their result.
         run: |
           set -euxo pipefail
-          cd $ANSIBLE_REPO
           xmlstarlet sel -t -m '//testcase[failure]' -v \
-          'concat(properties/property[@name="cukinia.id"]/@value, " | ", @classname, " | ", @name)'  -n cukinia_node*.xml | \
-          grep -Ev '^SEAPATH-(00109|00028|00031|00032)\b' > test_results || true
+          'concat(properties/property[@name="cukinia.id"]/@value, " | ", @classname, " | ", @name)'  -n ${{ env.RESULTS_FOLDER }}/cukinia_node*.xml | \
+          grep -Ev '^SEAPATH-(00109|00028|00031|00032|00084|00223|00033|00207|00047|00203|00198)\b' > cukinia_test_results || true
 
-          if grep -qE 'SEAPATH-[0-9]{5}' test_results; then
-            echo "Cukinia test fails"
-            exit 1
+          if grep -qE 'SEAPATH-[0-9]{5}' cukinia_test_results; then
+            echo "::error title=Hypervisor::Test fails, see associated test report"
+            echo "FAILED=true" >> "$GITHUB_ENV"
           fi
 
       - name: Test VM migration
         run: |
           cd $VIRTUAL_CLUSTER_REPO
           sg libvirt -c 'make ansible-vm-migration'
+
+      - name: Templatize system information
+        uses: cuchi/jinja2-action@8bd801365a8d36a0b20f45ee969161685de7785a # v1.3.0
+        with:
+          template: ${{ env.ANSIBLE_REPO }}/.github/test-report/system_info.adoc.j2
+          output_file: test-report-pdf/include/system_info.adoc
+          strict: true
+          data_file: "${{ env.RESULTS_FOLDER }}/hypervisors_facts.json"
+
+      - name: Templatize system information
+        uses: cuchi/jinja2-action@8bd801365a8d36a0b20f45ee969161685de7785a # v1.3.0
+        with:
+          template: ${{ env.ANSIBLE_REPO }}/.github/test-report/system_info.adoc.j2
+          output_file: test-report-pdf/include/system_info.adoc
+          strict: true
+          data_file: "${{ env.RESULTS_FOLDER }}/hypervisors_facts.json"
+
+
+      - name: Templatize notes
+        uses: cuchi/jinja2-action@8bd801365a8d36a0b20f45ee969161685de7785a # v1.3.0
+        with:
+          template: ${{ env.ANSIBLE_REPO }}/.github/test-report/notes.adoc.j2
+          output_file: test-report-pdf/include/notes.adoc
+          strict: true
+          data_file: "${{ env.RESULTS_FOLDER }}/data.json"
+          # uses env variables to populate the document
+
+      - name: Generate test report
+        working-directory: test-report-pdf
+        run: |
+          cp ${{ env.ANSIBLE_REPO }}/test_results/* include/
+          compliance_matrices=()
+          if [[ -n "${{ inputs.compliance_matrices_folder }}" ]]; then
+            for matrix in ${{ env.ANSIBLE_REPO }}/.github/test-report/bp28-compliance-matrices/${{ inputs.compliance_matrices_folder }}/*; do
+              matrix_name="$(basename $matrix)"
+              echo "Found compliance matrix $matrix_name"
+              compliance_matrices+=(--compliance_matrix "/report/bp28-compliance-matrices/${{ inputs.compliance_matrices_folder }}/$matrix_name")
+            done
+          fi
+
+          CQFD_EXTRA_RUN_ARGS="-v $(realpath ${{ env.ANSIBLE_REPO }}/.github/test-report):/report" \
+          cqfd exec ./compile.py \
+            --contact_email "seapath@savoirfairelinux.com" \
+            --client_name "SEAPATH" \
+            --project_name "SEAPATH" \
+            --subtitle "SEAPATH virtual cluster" \
+            --add_machine_name \
+            --pdf_themes_dir "/report/seapath-themes" \
+            --include_dir "./include" \
+            ${compliance_matrices[@]} \
+            --allow_absent \
+            --merge_compliance_matrices \
+            --show_failed_cdata
+
+          mv test-report.pdf "SEAPATH SEAPATH virtual cluster Tests Report.pdf"
+
+      - name: Upload test report
+        uses: actions/upload-artifact@v7
+        with:
+          path: test-report-pdf/*.pdf
+          if-no-files-found: error
+          archive: false
 
       - name: Diagnostics on failure
         if: failure()
@@ -265,3 +398,11 @@ jobs:
           done
           free -h
           df -h
+
+      # When the workflow detects a failing test, it does not stop the workflow
+      # directly. Thus, we fail this workflow at the end if one failing test
+      # has been previously detected.
+      - name: Fail if needed
+        if: "${{ env.FAILED == 'true' }}"
+        run: |
+          exit 1
